CREATE OR REPLACE TEMP TABLE SILVER.PASSENGER_FLIGHT_TEMP AS
SELECT
    AIRLINE, IATA_CD, FLIGHT_CD, TERMINAL, SCHEDULED_TM, ESTIMATED_TM, STATUS, FLIGHT_TYPE
FROM BRONZE.BR_3DAYS_ARRIVALS_DAILY
UNION ALL
SELECT
    AIRLINE, IATA_CD, FLIGHT_CD, TERMINAL, SCHEDULED_TM, ESTIMATED_TM, STATUS, FLIGHT_TYPE
FROM BRONZE.BR_3DAYS_DEPARTURE_DAILY;

CREATE OR REPLACE TABLE SILVER.SL_3DAYS_DAILY_MERGED AS
SELECT
    t.*,
    AIRPORT_NAME_KOR, NATION_NAME_KOR, REGION, CITY_KOR
FROM SILVER.PASSENGER_FLIGHT_TEMP t
JOIN BRONZE.BR_WORLD_AIRPORTS_INFO_STATIC a ON t.IATA_CD = a.IATA_CODE