CREATE OR REPLACE TABLE GOLD.GD_3DAYS_HOURLY_COUNT_DAILY AS
WITH HOUR AS (
    SELECT SEQ4() AS TIME_SLOT
    FROM TABLE(GENERATOR(ROWCOUNT => 24))
),
STATUS AS (
    SELECT COLUMN1 AS STATUS
    FROM VALUES ('도착'), ('출발')
),
RAW AS (
    SELECT
        HOUR(TO_TIMESTAMP(SCHEDULED_TM)) AS TIME_SLOT,
        STATUS,
        COUNT(*) AS CNT
    FROM SILVER.SL_3DAYS_DAILY_MERGED
    GROUP BY 1, 2
)
SELECT
    h.TIME_SLOT,
    s.STATUS,
    COALESCE(r.CNT, 0) AS CNT
FROM HOUR h
CROSS JOIN STATUS s
LEFT JOIN RAW r ON h.TIME_SLOT = r.TIME_SLOT AND s.STATUS = r.STATUS
ORDER BY h.TIME_SLOT, s.STATUS;