CREATE OR REPLACE TABLE GOLD.GD_MONTH_AIRLINE_ROUTES AS
/* 월별 항공사 노선 수 */
SELECT
    TO_CHAR(DEPARTURE_DT, 'MM') AS MONTH,
    COUNT(*) AS FLIGHT_COUNT
FROM SILVER.SL_ALL_AIRPORT_INFO_STATIC
GROUP BY 1
ORDER BY FLIGHT_COUNT DESC;
