CREATE OR REPLACE TABLE GOLD.GD_TOP10_AIRLINE_ROUTES AS
/* 항공사 별 노선수 */
SELECT
    AIRLINE,
    COUNT(*) AS FLIGHT_COUNT
FROM SILVER.SL_ALL_AIRPORT_INFO_STATIC
GROUP BY AIRLINE
ORDER BY FLIGHT_COUNT DESC
LIMIT 10;

