CREATE OR REPLACE TABLE GOLD.GD_TOP10_DESTINATION AS
/* 목적지별 노선 수 */
SELECT
    NATION_NM_KOR,
    CITY_KOR,
    AIRPORT_NM_KOR,
    IATA_CD,
    COUNT(*) AS FLIGHT_COUNT
FROM SILVER.SL_ALL_AIRPORT_INFO_STATIC
GROUP BY IATA_CD, AIRPORT_NM_KOR, CITY_KOR, NATION_NM_KOR
ORDER BY FLIGHT_COUNT DESC
LIMIT 10;