
CREATE OR REPLACE TABLE SILVER.SL_AIRPORT_INFO_7DAYS AS
WITH week7 AS (

    SELECT
    s.DATE AS DEPARTURE_DT,
    s.TIME AS DEPARTURE_TM,
    s.AIRLINE,
    s.FLIGHT AS FLIGHT_CD,
    s.AIRPORT AS DESTINATION,
    s.IATA_CODE AS IATA_CODE,

    w.AIRPORT_NAME_ENG AS AIRPORT_NM_ENG,
    w.AIRPORT_NAME_KOR AS AIRPORT_NM_KOR,
    w.NATION_NAME_ENG AS NATION_NM_ENG,
    w.NATION_NAME_KOR AS NATION_NM_KOR,
    w.CITY_ENG,
    w.CITY_KOR,
    w.LATITUDE,
    w.LONGITUDE

FROM BRONZE.BR_AIRPORT_SCHEDULE_7_DAILY s
LEFT JOIN BRONZE.BR_WORLD_AIRPORTS_INFO_STATIC w
    ON upper(s.IATA_CODE) = upper(w.IATA_CODE)
), 

dedup AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY 
                DEPARTURE_DT,
                DEPARTURE_TM,
                AIRLINE,
                FLIGHT_CD,
                IATA_CD
            ORDER BY DEPARTURE_DT
        ) AS rn
    FROM week7
)

SELECT 
    DEPARTURE_DT,
    DEPARTURE_TM,
    AIRLINE,
    FLIGHT_CD,
    DESTINATION,
    IATA_CD,
    AIRPORT_NM_ENG,
    AIRPORT_NM_KOR,
    NATION_NM_ENG,
    NATION_NM_KOR,
    CITY_ENG,
    CITY_KOR,
    LATITUDE,
    LONGITUDE
FROM dedup
WHERE rn = 1;
