CREATE OR REPLACE TABLE SILVER.SL_ALL_AIRPORT_INFO_STATIC AS
WITH yearly AS (
    SELECT
        /* FLIGHT_DATE: NUMBER → DATE 변환 */
        TO_DATE(TO_VARCHAR(s.FLIGHT_DATE), 'YYYYMMDD') AS DEPARTURE_DT,
        s.SCHEDULED_TIME AS DEPARTURE_TM,
        s.AIRLINE,
        s.FLIGHT_NUMBER AS FLIGHT_CD,
        s.DESTINATION,

        /* 세계 공항 정보 매핑 */
        w.IATA_CODE AS IATA_CD,
        w.AIRPORT_NAME_ENG AS AIRPORT_NM_ENG,
        w.AIRPORT_NAME_KOR AS AIRPORT_NM_KOR,
        w.NATION_NAME_ENG AS NATION_NM_ENG,
        w.NATION_NAME_KOR AS NATION_NM_KOR,
        w.CITY_ENG,
        w.CITY_KOR,
        w.LATITUDE,
        w.LONGITUDE
    FROM BRONZE.BR_AIRPORT_SCHEDULE_STATIC_YEARLY s
    LEFT JOIN BRONZE.BR_WORLD_AIRPORTS_INFO_STATIC w
        ON UPPER(s.DESTINATION) = UPPER(w.CITY_KOR)
),

dedup AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY 
                DEPARTURE_DT,
                DEPARTURE_TM,
                AIRLINE,
                FLIGHT_CD,
                IATA_CD
            ORDER BY DEPARTURE_DT
        ) AS rn
    FROM yearly
)

SELECT 
    DEPARTURE_DT,
    DEPARTURE_TM,
    AIRLINE,
    FLIGHT_CD,
    DESTINATION,
    IATA_CD,
    AIRPORT_NM_ENG,
    AIRPORT_NM_KOR,
    NATION_NM_ENG,
    NATION_NM_KOR,
    CITY_ENG,
    CITY_KOR,
    LATITUDE,
    LONGITUDE
FROM dedup
WHERE rn = 1;